name: Flutter iOS Build for AltStore (Client)

on:
  push:
    branches: [ main, master ] # Сработает для веток main или master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod install --repo-update
        cd ..

    - name: Build Flutter iOS (No Sign)
      run: |
        flutter build ios --no-codesign --release

    - name: Prepare APP folder for AltStore
      run: |
        mkdir -p Payload
        
        # Заходим в папку скомпилированного приложения
        cd build/ios/iphoneos/
        
        # Автоматически находим готовый .app файл, как бы он ни назывался
        REAL_APP=$(ls -d *.app | head -n 1)
        
        if [ -z "$REAL_APP" ]; then
          echo "Ошибка: В папке сборки не найдено ни одного .app файла!"
          exit 1
        fi
        
        echo "Успешно нашли приложение: $REAL_APP"
        
        # Копируем приложение в Payload и архивируем в .ipa
        cp -r "$REAL_APP" ../../../Payload/
        cd ../../../
        zip -r Client.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: client-ios-app
        path: Client.ipa
